// protoc-gen-hrpc: a protoc plugin that generates hrpc service stubs.
//
//   protoc --plugin=protoc-gen-hrpc=./protoc-gen-hrpc \
//          --cpp_out=. --hrpc_out=. calc.proto
//
// For each `service S { rpc M (Req) returns (Resp); }` it emits <base>.hrpc.h:
//   - class SService : public hv::rpc::RpcService  (server base, pure virtuals)
//   - class SStub                                  (client stub, sync + async)
//
// protoc supplies the parsed AST on stdin (CodeGeneratorRequest); we only walk
// ServiceDescriptor and fill a template -- no IDL parsing here.

#include <google/protobuf/compiler/code_generator.h>
#include <google/protobuf/compiler/plugin.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/printer.h>
#include <google/protobuf/io/zero_copy_stream.h>

#include <map>
#include <memory>
#include <string>
#include <vector>

using namespace google::protobuf;
using namespace google::protobuf::compiler;

namespace {

// "package.Message" -> "package::Message" C++ qualified name.
std::string CppType(const Descriptor* d) {
    std::string name(d->full_name());
    std::string out;
    for (char c : name) out += (c == '.') ? std::string("::") : std::string(1, c);
    return "::" + out;
}

// Strip the ".proto" suffix but keep the directory, matching protoc --cpp_out
// (which writes sub/x.pb.h for sub/x.proto). Returns "sub/x" for "sub/x.proto".
std::string StripProtoExt(const std::string& filename) {
    std::string s = filename;
    size_t dot = s.rfind(".proto");
    if (dot != std::string::npos) s = s.substr(0, dot);
    return s;
}

// The base name (no directory) of a stripped path, for the include guard.
std::string LeafName(const std::string& path) {
    size_t slash = path.find_last_of('/');
    return (slash != std::string::npos) ? path.substr(slash + 1) : path;
}

class HrpcGenerator : public CodeGenerator {
public:
    bool Generate(const FileDescriptor* file, const std::string& /*parameter*/,
                  GeneratorContext* ctx, std::string* /*error*/) const override {
        if (file->service_count() == 0) return true;

        std::string base = StripProtoExt(std::string(file->name())); // e.g. "sub/x"
        std::string header = base + ".hrpc.h";                        // written as sub/x.hrpc.h
        std::string leaf = LeafName(base);                            // "x"

        std::unique_ptr<io::ZeroCopyOutputStream> out(ctx->Open(header));
        io::Printer p(out.get(), '$');

        std::string guard = "HRPC_GEN_" + leaf + "_H_";
        p.Print("// Generated by protoc-gen-hrpc. DO NOT EDIT.\n");
        p.Print("#ifndef $guard$\n#define $guard$\n\n", "guard", guard);
        p.Print("#include \"RpcServer.h\"\n");
        p.Print("#include \"RpcClient.h\"\n");
        // x.hrpc.h and x.pb.h live in the same output directory, so the leaf
        // name resolves via a quoted include.
        p.Print("#include \"$leaf$.pb.h\"\n\n", "leaf", leaf);

        // Generate services inside the proto's package namespace (a.b -> namespace a { namespace b {),
        // so services in different packages don't collide in the global scope.
        std::string pkg(file->package());
        std::vector<std::string> ns;
        for (size_t start = 0; start <= pkg.size(); ) {
            size_t dot = pkg.find('.', start);
            std::string part = pkg.substr(start, dot == std::string::npos ? std::string::npos : dot - start);
            if (!part.empty()) ns.push_back(part);
            if (dot == std::string::npos) break;
            start = dot + 1;
        }
        for (auto& n : ns) p.Print("namespace $n$ {\n", "n", n);
        if (!ns.empty()) p.Print("\n");

        for (int i = 0; i < file->service_count(); ++i) {
            GenerateService(file->service(i), &p);
        }

        for (size_t i = ns.size(); i-- > 0; ) p.Print("} // namespace $n$\n", "n", ns[i]);
        if (!ns.empty()) p.Print("\n");

        p.Print("#endif // $guard$\n", "guard", guard);
        return true;
    }

    uint64_t GetSupportedFeatures() const override {
        return FEATURE_PROTO3_OPTIONAL;
    }

private:
    void GenerateService(const ServiceDescriptor* svc, io::Printer* p) const {
        std::map<std::string, std::string> vars;
        vars["svc"] = std::string(svc->name());
        vars["fqsvc"] = std::string(svc->full_name());

        // ---- Server base ----
        p->Print(vars, "// ===== service $svc$ =====\n");
        p->Print(vars, "class $svc$Service : public hv::rpc::RpcService {\n");
        p->Print("public:\n");
        p->Indent();
        p->Print(vars, "$svc$Service() {\n");
        p->Indent();
        for (int i = 0; i < svc->method_count(); ++i) {
            const MethodDescriptor* m = svc->method(i);
            std::map<std::string, std::string> mv = vars;
            mv["method"] = std::string(m->name());
            mv["req"] = CppType(m->input_type());
            mv["resp"] = CppType(m->output_type());
            p->Print(mv,
                "addMethod(\"$fqsvc$.$method$\", [this](const std::string& reqData, std::string* respData) {\n");
            p->Indent();
            p->Print(mv, "$req$ req; $resp$ resp;\n");
            p->Print("if (!req.ParseFromString(reqData)) return hv::rpc::RpcStatus(hv::rpc::HRPC_STATUS_BAD_REQUEST, \"parse request failed\");\n");
            p->Print(mv, "hv::rpc::RpcStatus st = $method$(req, &resp);\n");
            p->Print("if (st.ok()) resp.SerializeToString(respData);\n");
            p->Print("return st;\n");
            p->Outdent();
            p->Print("});\n");
        }
        p->Outdent();
        p->Print("}\n");
        p->Print(vars, "const char* serviceName() const override { return \"$fqsvc$\"; }\n");
        for (int i = 0; i < svc->method_count(); ++i) {
            const MethodDescriptor* m = svc->method(i);
            std::map<std::string, std::string> mv = vars;
            mv["method"] = std::string(m->name());
            mv["req"] = CppType(m->input_type());
            mv["resp"] = CppType(m->output_type());
            p->Print(mv, "virtual hv::rpc::RpcStatus $method$(const $req$& req, $resp$* resp) = 0;\n");
        }
        p->Outdent();
        p->Print("};\n\n");

        // ---- Client stub ----
        p->Print(vars, "class $svc$Stub {\n");
        p->Print("public:\n");
        p->Indent();
        p->Print(vars, "explicit $svc$Stub(hv::rpc::RpcClient* client) : client_(client) {}\n");
        for (int i = 0; i < svc->method_count(); ++i) {
            const MethodDescriptor* m = svc->method(i);
            std::map<std::string, std::string> mv = vars;
            mv["method"] = std::string(m->name());
            mv["req"] = CppType(m->input_type());
            mv["resp"] = CppType(m->output_type());
            // sync
            p->Print(mv, "hv::rpc::RpcStatus $method$(const $req$& req, $resp$* resp, int timeout_ms = 10000) {\n");
            p->Indent();
            p->Print("std::string reqData, respData;\n");
            p->Print("req.SerializeToString(&reqData);\n");
            p->Print(mv, "hv::rpc::RpcStatus st = client_->call(\"$fqsvc$.$method$\", reqData, &respData, timeout_ms);\n");
            p->Print("if (st.ok() && resp && !resp->ParseFromString(respData))\n");
            p->Print("    return hv::rpc::RpcStatus(hv::rpc::HRPC_STATUS_BAD_REQUEST, \"parse response failed\");\n");
            p->Print("return st;\n");
            p->Outdent();
            p->Print("}\n");
            // async
            p->Print(mv, "void $method$(const $req$& req, std::function<void(const hv::rpc::RpcStatus&, const $resp$&)> cb, int timeout_ms = 10000) {\n");
            p->Indent();
            p->Print("std::string reqData;\n");
            p->Print("req.SerializeToString(&reqData);\n");
            p->Print(mv, "client_->callAsync(\"$fqsvc$.$method$\", reqData, [cb](const hv::rpc::RpcStatus& st, const std::string& respData) {\n");
            p->Indent();
            p->Print(mv, "$resp$ resp;\n");
            p->Print("if (st.ok() && !resp.ParseFromString(respData)) {\n");
            p->Print("    if (cb) cb(hv::rpc::RpcStatus(hv::rpc::HRPC_STATUS_BAD_REQUEST, \"parse response failed\"), resp);\n");
            p->Print("    return;\n");
            p->Print("}\n");
            p->Print("if (cb) cb(st, resp);\n");
            p->Outdent();
            p->Print("}, timeout_ms);\n");
            p->Outdent();
            p->Print("}\n");
        }
        p->Outdent();
        p->Print("private:\n");
        p->Print("    hv::rpc::RpcClient* client_;\n");
        p->Print("};\n\n");
    }
};

} // namespace

int main(int argc, char* argv[]) {
    HrpcGenerator generator;
    return PluginMain(argc, argv, &generator);
}
